name: CI/CD - React + Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧪 Run Playwright tests
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: 📊 Upload Playwright report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
